// <auto-generated />
using System;
using FilmSitesiData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilmSitesiData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FilmSitesiModel.Models.Adminler", b =>
                {
                    b.Property<int>("AdminNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("AdminMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("AdminSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("AdminTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("AdminNo");

                    b.ToTable("Adminlers");
                });

            modelBuilder.Entity("FilmSitesiModel.Models.FilmEkibi", b =>
                {
                    b.Property<int>("EkipNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FilmNo")
                        .HasColumnType("int");

                    b.Property<int?>("FilmlersFilmNo")
                        .HasColumnType("int");

                    b.Property<int>("OyuncuNo")
                        .HasColumnType("int");

                    b.Property<int>("YonetmenNo")
                        .HasColumnType("int");

                    b.Property<int?>("YonetmensYonetmenNo")
                        .HasColumnType("int");

                    b.HasKey("EkipNo");

                    b.HasIndex("FilmlersFilmNo");

                    b.HasIndex("OyuncuNo");

                    b.HasIndex("YonetmensYonetmenNo");

                    b.ToTable("FilmEkibis");
                });

            modelBuilder.Entity("FilmSitesiModel.Models.Filmler", b =>
                {
                    b.Property<int>("FilmNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FilmAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("FilmSuresi")
                        .HasColumnType("int");

                    b.Property<string>("FilmTur")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("FilmYayinlamaTarih")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("YonetmenNo")
                        .HasColumnType("int");

                    b.Property<int?>("YonetmensYonetmenNo")
                        .HasColumnType("int");

                    b.HasKey("FilmNo");

                    b.HasIndex("YonetmensYonetmenNo");

                    b.ToTable("Filmlers");
                });

            modelBuilder.Entity("FilmSitesiModel.Models.Kullanicilar", b =>
                {
                    b.Property<int>("KullaniciNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("KullaniciMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("KullaniciTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("KullaniciNo");

                    b.ToTable("Kullanicilars");
                });

            modelBuilder.Entity("FilmSitesiModel.Models.Oyuncular", b =>
                {
                    b.Property<int>("OyuncuNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OynadigiFilmSayisi")
                        .HasColumnType("int")
                        .HasMaxLength(3);

                    b.Property<string>("OyuncuAdiSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("OyuncuCinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("OyuncuDogumTarihi")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("OyuncuDogumYeri")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("OyuncuNo");

                    b.ToTable("Oyunculars");
                });

            modelBuilder.Entity("FilmSitesiModel.Models.Sinemalar", b =>
                {
                    b.Property<int>("SinemaNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("FilmNo")
                        .HasColumnType("int");

                    b.Property<int?>("FilmlersFilmNo")
                        .HasColumnType("int");

                    b.Property<string>("Sehri")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("SinemaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("SinemaNo");

                    b.HasIndex("FilmlersFilmNo");

                    b.ToTable("Sinemalars");
                });

            modelBuilder.Entity("FilmSitesiModel.Models.Yonetmen", b =>
                {
                    b.Property<int>("YonetmenNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("YonetmenAdiSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("YonetmenCinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("YonetmenDogumTarihi")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("YonetmenDogumYeri")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("YonetmenTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("YonetmenNo");

                    b.ToTable("Yonetmens");
                });

            modelBuilder.Entity("FilmSitesiModel.Models.Yorumlar", b =>
                {
                    b.Property<string>("YorumNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("FilmNo")
                        .HasColumnType("int");

                    b.Property<int?>("FilmlersFilmNo")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciNo")
                        .HasColumnType("int");

                    b.Property<int?>("KullanicilarsKullaniciNo")
                        .HasColumnType("int");

                    b.Property<int>("YildizSayisi")
                        .HasColumnType("int");

                    b.HasKey("YorumNo");

                    b.HasIndex("FilmlersFilmNo");

                    b.HasIndex("KullanicilarsKullaniciNo");

                    b.ToTable("Yorumlars");
                });

            modelBuilder.Entity("FilmSitesiModel.Models.joinModel1", b =>
                {
                    b.Property<int>("islemNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OyuncuNo")
                        .HasColumnType("int");

                    b.Property<int?>("filmekibiEkipNo")
                        .HasColumnType("int");

                    b.HasKey("islemNo");

                    b.HasIndex("OyuncuNo");

                    b.HasIndex("filmekibiEkipNo");

                    b.ToTable("Elemans");
                });

            modelBuilder.Entity("FilmSitesiModel.Models.FilmEkibi", b =>
                {
                    b.HasOne("FilmSitesiModel.Models.Filmler", "Filmlers")
                        .WithMany()
                        .HasForeignKey("FilmlersFilmNo");

                    b.HasOne("FilmSitesiModel.Models.Oyuncular", "Oyuncular")
                        .WithMany()
                        .HasForeignKey("OyuncuNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmSitesiModel.Models.Yonetmen", "Yonetmens")
                        .WithMany()
                        .HasForeignKey("YonetmensYonetmenNo");
                });

            modelBuilder.Entity("FilmSitesiModel.Models.Filmler", b =>
                {
                    b.HasOne("FilmSitesiModel.Models.Yonetmen", "Yonetmens")
                        .WithMany()
                        .HasForeignKey("YonetmensYonetmenNo");
                });

            modelBuilder.Entity("FilmSitesiModel.Models.Sinemalar", b =>
                {
                    b.HasOne("FilmSitesiModel.Models.Filmler", "Filmlers")
                        .WithMany()
                        .HasForeignKey("FilmlersFilmNo");
                });

            modelBuilder.Entity("FilmSitesiModel.Models.Yorumlar", b =>
                {
                    b.HasOne("FilmSitesiModel.Models.Filmler", "Filmlers")
                        .WithMany()
                        .HasForeignKey("FilmlersFilmNo");

                    b.HasOne("FilmSitesiModel.Models.Kullanicilar", "Kullanicilars")
                        .WithMany()
                        .HasForeignKey("KullanicilarsKullaniciNo");
                });

            modelBuilder.Entity("FilmSitesiModel.Models.joinModel1", b =>
                {
                    b.HasOne("FilmSitesiModel.Models.Oyuncular", "oyuncu")
                        .WithMany()
                        .HasForeignKey("OyuncuNo");

                    b.HasOne("FilmSitesiModel.Models.FilmEkibi", "filmekibi")
                        .WithMany()
                        .HasForeignKey("filmekibiEkipNo");
                });
#pragma warning restore 612, 618
        }
    }
}
